# create a conda env with 'conda env create -f environment.yml -prefix [path]'
channels:
  - conda-forge
  - conda-forge
  - bioconda
  - defaults
  - anaconda


dependencies:
  - python=3.10
  - pandas
  - scipy
  - pip
  - ipykernel
  - pip:
    - matplotlib
    - pandas
    - scikit-learn
    - openpyxl
    - seaborn
    - venn
    - lxml
    - pridepy
    - requests
    - pyopenms
    - ppx
    - pyteomics


